In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3],dtype = 'int8')
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,9],[2.3,4.5,6]])
print(b)

[[1.  2.  9. ]
 [2.3 4.5 6. ]]


In [5]:
b.itemsize

8

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.dtype

dtype('int8')

In [9]:
a = np.array([[1,2,3,3,5,6,7,8],[32,5,6,75,83,9,2,5,]])
a

array([[ 1,  2,  3,  3,  5,  6,  7,  8],
       [32,  5,  6, 75, 83,  9,  2,  5]])

In [10]:
a[0,4]

np.int64(5)

In [11]:

a[0,:5]

array([1, 2, 3, 3, 5])

In [12]:
a[:,2]

array([3, 6])

In [13]:
a[0, 0:7:2]

array([1, 3, 5, 7])

In [14]:
a[:,2] = 5
print(a)

[[ 1  2  5  3  5  6  7  8]
 [32  5  5 75 83  9  2  5]]


In [15]:
a[1,6] = 9
print(a)

[[ 1  2  5  3  5  6  7  8]
 [32  5  5 75 83  9  9  5]]


In [16]:
a = np.array([[[1,2],[2,4]],[[1,3],[4,6]]])
a

array([[[1, 2],
        [2, 4]],

       [[1, 3],
        [4, 6]]])

In [17]:
a[:,0,:]


array([[1, 2],
       [1, 3]])

In [18]:
a[:,1,:] = [[1,2],[1,4]]
a

array([[[1, 2],
        [1, 2]],

       [[1, 3],
        [1, 4]]])

In [19]:
np.zeros((5,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [21]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [22]:
np.full_like(a,69)

array([[[69, 69],
        [69, 69]],

       [[69, 69],
        [69, 69]]])

In [23]:
np.identity(5) # identify matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr = np.array([[[1,2,3], [2,3,3]]])
rep = np.repeat(arr,10,axis = -1)
print(rep)

[[[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]
  [2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]]


In [25]:
c = np.ones((5,5))
print(c)
b = np.zeros((3,3))
print(b)
b[1,1] = 9
print(b)
c[1:4,1:4] = b
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
a = np.array([1,3,4])
print(a)
b = a
b[0] = 2
print(b)

[1 3 4]
[2 3 4]


In [27]:
a = np.array([1,2,4,5,6,7])
print(a)

[1 2 4 5 6 7]


In [28]:
a+2

array([3, 4, 6, 7, 8, 9])

dc

In [29]:
a+2

array([3, 4, 6, 7, 8, 9])

In [30]:
a/2

array([0.5, 1. , 2. , 2.5, 3. , 3.5])

In [31]:
a-2

array([-1,  0,  2,  3,  4,  5])

In [32]:
a*2

array([ 2,  4,  8, 10, 12, 14])

In [33]:
a*a

array([ 1,  4, 16, 25, 36, 49])

In [34]:
b = np.array([1,23,45,6,79,3])
a/b

array([1.        , 0.08695652, 0.08888889, 0.83333333, 0.07594937,
       2.33333333])

In [35]:
a*b

array([  1,  46, 180,  30, 474,  21])

In [36]:
a+b

array([ 2, 25, 49, 11, 85, 10])

In [37]:
a-b

array([  0, -21, -41,  -1, -73,   4])

In [38]:
np.sin(b)

array([ 0.84147098, -0.8462204 ,  0.85090352, -0.2794155 , -0.44411267,
        0.14112001])

In [39]:
np.tan(a)

array([ 1.55740772, -2.18503986,  1.15782128, -3.38051501, -0.29100619,
        0.87144798])

In [40]:
np.cos(b/a)

array([0.54030231, 0.48330476, 0.25168965, 0.36235775, 0.82516842,
       0.90956035])

In [41]:
b = np.ones((2,3))
print(a)
a = np.full((3,2),99)
print(b)
np.matmul(a,b)

[1 2 4 5 6 7]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[198., 198., 198.],
       [198., 198., 198.],
       [198., 198., 198.]])

In [44]:


c = np.identity(5)
trans = np.transpose(c)
det = np.linalg.det(c)
inv = np.linalg.inv(c)
trace = np.trace(c)  

print("Transpose:")
print(trans)
print("Determinant:", det)
print("Inverse:")
print(inv)
print("Trace:", trace)


Transpose:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Determinant: 1.0
Inverse:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Trace: 5.0


In [107]:
a = np.array([[1,2,3],[2,4,5]])
a

array([[1, 2, 3],
       [2, 4, 5]])

In [114]:
np.min(a, axis = 0)

array([1, 2, 3])

In [115]:
np.max(a, axis = 0)

array([2, 4, 5])

In [123]:
before = np.array([[1,2,3],[1,4,5]])
print(before)
print("    ")
after = before.reshape((3,2))
print(after)

[[1 2 3]
 [1 4 5]]
    
[[1 2]
 [3 1]
 [4 5]]


In [60]:
v1 = np.array([1,2,3,4])
v2 =np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [64]:
h1 = np.zeros([2,2])
h2 = np.ones([2,3])

np.hstack([h1,h2,h1])

array([[0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.]])

In [81]:
data = np.genfromtxt('data.txt', delimiter=',', usecols=np.arange(14))
print(data)



[[  1.   2.   3.   4.   4.   4.   5.   5.   6.   2.   1.   5.   3.   5.]
 [  2.   4.   5.   2.   2.   5.   7.   9.   7.   8.   8.   4.   9.   4.]
 [  3.   6.   8.   1.   6.   8.  24.   8.   4.  73.  82.  82. 825.  82.]]


In [82]:
data>50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
         True,  True,  True,  True,  True]])

In [83]:
data[data>50]

array([ 73.,  82.,  82., 825.,  82.])

In [85]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,4]]

array([2, 4, 5])

In [86]:
((data>50)&(data<100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
         True,  True,  True, False,  True]])

In [87]:
(~(data>50)&(data<100))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False]])