<h3>Objectives:</h3>

<ul>Understand what arrays are and why they are useful.</ul>
<ul>Learn how to create and manipulate arrays using Python lists.</ul>
<ul>Explore NumPy for more efficient array operations.</ul>
<ul>Implement small exercises for hands-on practice.</ul>

<h3>1. What are Arrays?</h3>
<p>An array is a collection of items stored at contiguous memory locations. In Python, arrays can be represented using lists or libraries like NumPy. Arrays are useful for:</p>

<ul>Storing data of the same type.</ul>
<ul>Performing mathematical operations efficiently.</ul>

<h3>2. Arrays Using Python Lists</h3>
<p>In Python, the closest native data type to an array is a list. While not as efficient as NumPy arrays for numerical operations, lists are dynamic, allowing mixed data types.</p>
<h4>Creating a List (Array):</h4>

In [1]:
# A simple list (array) of integers
numbers = [10, 20, 30, 40, 50]
print("Array:", numbers)

# A list (array) with different data types
mixed_array = [1, "apple", 3.14, True]
print("Mixed Array:", mixed_array)

Array: [10, 20, 30, 40, 50]
Mixed Array: [1, 'apple', 3.14, True]


<h4>Accessing Array Elements:</h4>
<p>You can access elements in a list using indices.</p>

In [3]:
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])

First Element: 10
Last Element: 50


<h4>Modifying Arrays:</h4>
<p>Lists are mutable, meaning you can change their elements.</p>

In [5]:
numbers[1] = 25
print("Modified Array:", numbers)

Modified Array: [10, 25, 30, 40, 50]


<h4>Array Operations:</h4>
<p>You can perform basic operations on lists.</p>

In [7]:
# Adding elements to a list
numbers.append(60)
print("After Append:", numbers)

# Removing an element
numbers.remove(30)
print("After Remove:", numbers)

After Append: [10, 25, 30, 40, 50, 60]
After Remove: [10, 25, 40, 50, 60]


<h3>3. Arrays with NumPy</h3>
<p>For numerical operations, Python's NumPy library provides more powerful and efficient arrays. NumPy arrays are faster and can handle larger datasets than lists.</p>

<h4>Creating NumPy Arrays:</h4>

In [10]:
import numpy as np

# Creating a NumPy array
arr = np.array([10, 20, 30, 40, 50])
print("NumPy Array:", arr)

NumPy Array: [10 20 30 40 50]


<h4>NumPy Array Characteristics:</h4>
<ul><b>Homogeneous</b>: All elements in a NumPy array are of the same type. </ul>
<ul><b>Efficient</b>: NumPy arrays are more memory-efficient than Python lists.</ul>

<h4>Array Operations in NumPy:</h4>
<p>NumPy allows you to perform element-wise operations.</p>
    

In [11]:
# Adding 5 to each element
arr_add = arr + 5
print("After Addition:", arr_add)

# Multiplying each element by 2
arr_mul = arr * 2
print("After Multiplication:", arr_mul)

After Addition: [15 25 35 45 55]
After Multiplication: [ 20  40  60  80 100]


<h4>Multi-Dimensional Arrays:</h4>
<p>NumPy also supports multi-dimensional arrays, which are essential for working with matrices and tensors.</p>

In [12]:
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array (Matrix):\n", matrix)

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]


<b>Reshaping arrays</b> is a fundamental concept in NumPy that allows you to change the shape of an array without changing its data. This can be particularly useful when you need to prepare data for machine learning, image processing, or any other application where data needs to be in a specific format.

In [19]:
# 1. Introduction to Reshaping
# Reshaping an array means changing its dimensions. This can be done using the reshape() method.

import numpy as np

# Create a 1D array
array_1d = np.arange(18)  # Creates an array with values from 0 to 11
print("Original 1D Array:", array_1d)

# Reshape to a 2D array (3 rows, 4 columns)
array_2d = array_1d.reshape(3, 6)
print("\nReshaped 2D Array (3x6):\n", array_2d)

# Reshape to a 3D array (2 layers, 2 rows, 3 columns)
array_3d = array_1d.reshape(2, 3, 3)
print("\nReshaped 3D Array (2x2x3):\n", array_3d)


Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

Reshaped 2D Array (3x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Reshaped 3D Array (2x2x3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [20]:
# 2. Understanding Dimensions
# Let's discuss the concept of dimensions (also known as axes) and how reshaping works with them.

# Check the shape of the original array
print("Shape of Original Array:", array_1d.shape)

# Check the shape of the 2D array
print("Shape of 2D Array:", array_2d.shape)

# Check the shape of the 3D array
print("Shape of 3D Array:", array_3d.shape)


Shape of Original Array: (18,)
Shape of 2D Array: (3, 6)
Shape of 3D Array: (2, 3, 3)


In [21]:
# 3. Using -1 in Reshape
# You can use -1 in the reshape method to automatically calculate the size of that dimension.

# Reshape using -1
reshaped_array = array_1d.reshape(3, -1)  # Automatically determines the second dimension
print("\nReshaped Array with -1:\n", reshaped_array)

# You can also reshape to a 1D array
reshaped_array_1d = array_2d.reshape(-1)
print("\nFlattened Array (1D) from 2D Array:\n", reshaped_array_1d)



Reshaped Array with -1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Flattened Array (1D) from 2D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [26]:
# 4. Reshaping with Compatibility
# It’s important that the total number of elements remains the same after reshaping.

# Trying to reshape to incompatible dimensions
try:
    array_incompatible = array_1d.reshape(3, 6)  # This will raise an error
except ValueError as e:
    print("\nError:", e)

# Valid reshape
array_valid = array_1d.reshape(6, 3)
print("Valid Reshape (4x3):\n", array_valid)

Valid Reshape (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [29]:
# 5. Example: Reshaping for Machine Learning
# Reshaping is often used to prepare data for machine learning models.

# Simulate a dataset with 2 features
data = np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

# Original shape
print("Original Data Shape:", data.shape)

# Reshape to a single feature (4 samples, 2 features)
reshaped_data = data.reshape(-1, 2)
print(reshaped_data)
print("\nReshaped Data Shape (4 samples, 2 features):", reshaped_data.shape)

# Reshape to have only one feature (8 samples, 1 feature)
reshaped_single_feature = data.reshape(-1, 1)
print(reshaped_single_feature)
print("Reshaped Data Shape (8 samples, 1 feature):", reshaped_single_feature.shape)

Original Data Shape: (4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Reshaped Data Shape (4 samples, 2 features): (4, 2)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Reshaped Data Shape (8 samples, 1 feature): (8, 1)


<h3>4. Practical Examples</h3>
<p>Here are some real-world examples where arrays are useful:</p>
    
<h4>Example 1: Temperature Data</h4>
<p>You can store daily temperatures for a week in an array:</p>

In [ ]:
temperatures = np.array([21.5, 22.3, 19.8, 23.1, 24.5, 20.2, 18.6])
print("Weekly Temperatures:", temperatures)

# Calculate the average temperature
avg_temp = np.mean(temperatures)
print("Average Temperature:", avg_temp)

<h4>Example 2: Image Representation</h4>
<p>Images can be represented as multi-dimensional arrays (matrices), where each element is a pixel value.</p>

In [ ]:
# Example 3x3 grayscale image
image = np.array([[255, 128, 0],
                  [128, 64, 32],
                  [0, 32, 64]])
print("Image as an Array:\n", image)

<h3>5. Exercises </h3>
<h4>Exercise 1: Create and Manipulate Lists</h4>

<p><ul>Create a list of 5 favorite fruits.</ul>
<ul>Add two more fruits to the list.</ul>
<ul>Replace the second fruit with "Strawberry".</ul>
<ul>Remove the last fruit from the list.</ul></p>

<h4>Exercise 2: Basic NumPy Array Operations</h4>
<p><ul>Create a NumPy array with 6 numbers.</ul>
<ul>Multiply each element by 3.</ul>
<ul>Find the sum of all elements.</ul>
<ul>Reshape the array into a 2x3 matrix.</ul></p>

<h4>Exercise 3: Advanced NumPy Practice</h4>
<p><ul>Create a 3x3 identity matrix using NumPy.</ul>
<ul>Generate an array of 10 random numbers between 1 and 100.</ul>
<ul>Sort the array in descending order.</ul></p>

<h3>3. Virtual Environments in Python</h3>

<p>A virtual environment is a self-contained directory where you can install packages and manage dependencies for each project. It ensures each project remains isolated.</p>

<h4>Creating a Virtual Environment:</h4>
<p>To create a virtual environment, use the following command:</p>

In [ ]:
# Python 3
python -m venv my_env

<h4>Activating the Virtual Environment:</h4>
<ul>On Windows</ul>

In [ ]:
my_env\Scripts\activate

<ul>On macOS/Linux:</ul>

In [ ]:
source my_env/bin/activate

<p>Once activated, any package you install will be specific to that environment.</p>

In [ ]:
pip install numpy pandas

<h4>Deactivating the Virtual Environment:</h4>
<p>To leave the environment, simply type:</p>

<b>deactivate</b>

<h3>4. Introduction to Conda</h3>
<p>Conda is a package management and environment management system that comes with Anaconda and Miniconda. It allows you to create isolated environments and manage packages easily, even across multiple versions of Python.</p>

<h4>Installing Conda:</h4>
<ul>Anaconda: A full data science package that includes Conda and many pre-installed packages. Download from Anaconda.</ul>
<ul>Miniconda: A lightweight alternative to Anaconda, which only installs Conda and no additional packages. Download from Miniconda.</ul>
<h4>Why Use Conda?</h4>
<ul>Manage both Python and non-Python packages.</ul>
<ul>Isolate environments easily, avoiding conflicts.</ul>
<ul>Useful for data science and machine learning projects.</ul>

<h3>5. Managing Environments with Conda</h3>

<h4>Creating a Conda Environment:</h4>

In [ ]:
conda create --name my_env

You can specify the Python version as well:

In [ ]:
conda create --name my_env python=3.8

<h4>Activating a Conda Environment:</h4>

In [ ]:
conda activate my_env

<h4>Installing Packages:</h4>

Once the environment is activated, you can install packages using Conda:

In [ ]:
conda install numpy pandas

Conda also supports installing packages from pip:

In [ ]:
conda install pip
pip install seaborn

<h4>Deactivating a Conda Environment:</h4>

To deactivate the current environment, use:

In [ ]:
conda deactivate

<h4>Listing Conda Environments:</h4>
<p>To list all your environments:</p>

In [ ]:
conda env list

In [ ]:
<h4>Removing a Conda Environment:</h4>
<p>To delete an environment:</p>

In [ ]:
conda remove --name my_env --all

<h3>6. Comparing Virtual Environments and Conda Environments</h3>

<table>
  <thead>
    <tr>
      <th>Feature</th>
      <th>Python Virtual Environments</th>
      <th>Conda Environments</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Package Manager</td>
      <td>pip</td>
      <td>conda + pip</td>
    </tr>
    <tr>
      <td>Python Version Management</td>
      <td>No</td>
      <td>Yes</td>
    </tr>
    <tr>
      <td>Supports Non-Python Packages</td>
      <td>No</td>
      <td>Yes</td>
    </tr>
    <tr>
      <td>Speed</td>
      <td>Faster</td>
      <td>Slightly slower</td>
    </tr>
    <tr>
      <td>Built-in Package Management</td>
      <td>No</td>
      <td>Yes</td>
    </tr>
  </tbody>
</table>



<h4>When to Use Virtualenv:</h4>
<ul>If you prefer managing environments with pip and don’t need non-Python dependencies.</ul>

<h4>When to Use Conda:</h4>
<ul>If you are working on data science projects and need non-Python libraries or managing multiple versions of Python.</ul>